version: "3"
services:
  web:
    image: grpcweb/envoy
    ports:
      - "9211:9211"
    networks:
      - webnet
  grpc-server:
    image: grpcweb/hellogrpc
    environment:
    - DBNAME=grpc
    - USERNAME=postgres
    - PASSWORD=postgres
    - HOST=database
    - PORT=5432
    depends_on:
      - database
    networks:
      - webnet
  database:
    image: postgres:11.3-alpine
    environment:
    - POSTGRES_DB=grpc
    networks:
      - webnet
networks:
  webnet: